# Generated by Django 4.2.28 on 2026-02-16 05:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('admin_tasks', '0002_initial'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='class_assigned',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='students', to='admin_tasks.class'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='subjects',
            field=models.ManyToManyField(blank=True, related_name='teachers', to='admin_tasks.subject'),
        ),
    ]
