# Generated by Django 4.2.28 on 2026-02-18 04:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0003_doubt_doubtreply_teachersubjectassignment'),
        ('users', '0002_alter_customuser_class_assigned_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='class_assigned',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='students', to='academics.academicclass'),
        ),
    ]
