# Generated by Django 4.2.28 on 2026-02-18 04:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0003_doubt_doubtreply_teachersubjectassignment'),
        ('users', '0003_alter_customuser_class_assigned'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='subjects',
            field=models.ManyToManyField(blank=True, related_name='teachers', to='academics.subject'),
        ),
    ]
