# Generated by Django 4.2.10 on 2026-02-04 17:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_alter_customuser_otp_alter_customuser_otp_created_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='otp_purpose',
            field=models.CharField(blank=True, choices=[('registration', 'Registration'), ('password_reset', 'Password Reset')], max_length=20, null=True),
        ),
    ]
