# Generated by Django 4.2.28 on 2026-02-10 08:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('students', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='assignmentsubmission',
            old_name='text_submission',
            new_name='submitted_text',
        ),
        migrations.RemoveField(
            model_name='assignmentsubmission',
            name='file',
        ),
        migrations.AddField(
            model_name='assignmentsubmission',
            name='submitted_file',
            field=models.FileField(blank=True, null=True, upload_to='assignment_submissions/'),
        ),
        migrations.AlterField(
            model_name='assignmentsubmission',
            name='grade',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='testattempt',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='test_attempts', to=settings.AUTH_USER_MODEL),
        ),
    ]
