# Generated by Django 4.2.28 on 2026-02-16 05:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0002_alter_academicclass_options_alter_chapter_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('teachers', '0005_alter_attendance_unique_together_attendance_subject_and_more'),
        ('students', '0002_rename_text_submission_assignmentsubmission_submitted_text_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentacademicinfo',
            name='academic_class',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='academic_students', to='academics.academicclass'),
        ),
        migrations.AlterField(
            model_name='studentanswer',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='student_answers', to='teachers.question'),
        ),
        migrations.AlterField(
            model_name='studentanswer',
            name='selected_option',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='studentanswer',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='student_answers', to=settings.AUTH_USER_MODEL),
        ),
    ]
