# Generated by Django 4.2.10 on 2026-02-04 16:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('teachers', '0002_initial'),
        ('academics', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('students', '0003_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentanswer',
            name='attempt',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='students.testattempt'),
        ),
        migrations.AlterUniqueTogether(
            name='testattempt',
            unique_together={('student', 'test')},
        ),
        migrations.CreateModel(
            name='StudentAcademicInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('academic_class', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='academics.academicclass')),
                ('student', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='student_academic_info', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
