server {
    listen 80;
    server_name eduvibe.ddns.net;
    return 301 https://$host$request_uri;
}
server {
    listen 443 ssl;
    server_name eduvibe.ddns.net;
    ssl_certificate /etc/letsencrypt/live/eduvibe.ddns.net/fullchain.pem;
    ssl_certificate_key /etc/letsencrypt/live/eduvibe.ddns.net/privkey.pem;
    root /usr/share/nginx/html;
    index index.html;
    location /api/ {
        proxy_pass http://eduvibe-backend:8000/api/;
        proxy_set_header Host eduvibe.ddns.net;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_read_timeout 300;
    }
    location /django-admin/ {
        proxy_pass http://eduvibe-backend:8000/admin/;
        proxy_set_header Host eduvibe.ddns.net;
        proxy_set_header X-Real-IP $remote_addr;
    }
    location /static/ {
        proxy_pass http://eduvibe-backend:8000/static/;
        proxy_set_header Host eduvibe.ddns.net;
    }
    location / {
        try_files $uri $uri/ /index.html;
    }
}
