# Generated by Django 4.2.28 on 2026-02-16 10:11

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('admin_tasks', '0002_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='chapter',
            options={'ordering': ['subject', 'class_assigned', 'order', 'name'], 'verbose_name': 'Chapter', 'verbose_name_plural': 'Chapters'},
        ),
        migrations.AlterModelOptions(
            name='class',
            options={'ordering': ['name'], 'verbose_name': 'Class', 'verbose_name_plural': 'Classes'},
        ),
        migrations.AlterModelOptions(
            name='feepayment',
            options={'ordering': ['-payment_date'], 'verbose_name': 'Fee Payment', 'verbose_name_plural': 'Fee Payments'},
        ),
        migrations.AlterModelOptions(
            name='notification',
            options={'ordering': ['-created_at'], 'verbose_name': 'Notification', 'verbose_name_plural': 'Notifications'},
        ),
        migrations.AlterModelOptions(
            name='subject',
            options={'ordering': ['name']},
        ),
        migrations.RenameField(
            model_name='feepayment',
            old_name='paid_at',
            new_name='payment_date',
        ),
        migrations.AddField(
            model_name='chapter',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2026, 2, 16, 10, 10, 46, 527760, tzinfo=datetime.timezone.utc)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='chapter',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='chapter',
            name='order',
            field=models.IntegerField(default=0, help_text='Order of chapter in curriculum'),
        ),
        migrations.AddField(
            model_name='chapter',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='class',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2026, 2, 16, 10, 10, 59, 119156, tzinfo=datetime.timezone.utc)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='class',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='feepayment',
            name='month',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='feepayment',
            name='payment_method',
            field=models.CharField(choices=[('cash', 'Cash'), ('upi', 'UPI'), ('card', 'Card'), ('bank_transfer', 'Bank Transfer'), ('cheque', 'Cheque'), ('online', 'Online Payment')], default='cash', max_length=20),
        ),
        migrations.AddField(
            model_name='feepayment',
            name='payment_status',
            field=models.CharField(choices=[('pending', 'Pending'), ('completed', 'Completed'), ('failed', 'Failed'), ('refunded', 'Refunded')], default='completed', max_length=20),
        ),
        migrations.AddField(
            model_name='feepayment',
            name='receipt_number',
            field=models.CharField(default=datetime.datetime(2026, 2, 16, 10, 11, 7, 73570, tzinfo=datetime.timezone.utc), help_text='Auto-generated receipt number', max_length=50, unique=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='feepayment',
            name='recorded_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='recorded_payments', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='feepayment',
            name='remarks',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='feepayment',
            name='transaction_id',
            field=models.CharField(blank=True, help_text='Transaction/Reference ID', max_length=100),
        ),
        migrations.AddField(
            model_name='feepayment',
            name='year',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='notification',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sent_notifications', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='notification',
            name='is_read',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='notification',
            name='recipient_type',
            field=models.CharField(choices=[('all_students', 'All Students'), ('all_teachers', 'All Teachers'), ('all_users', 'Everyone'), ('individual', 'Specific User'), ('class_students', 'Students of Specific Class')], default='individual', max_length=20),
        ),
        migrations.AddField(
            model_name='notification',
            name='target_class',
            field=models.ForeignKey(blank=True, help_text='For class-specific notifications', null=True, on_delete=django.db.models.deletion.CASCADE, to='admin_tasks.class'),
        ),
        migrations.AddField(
            model_name='notification',
            name='title',
            field=models.CharField(default='Notification', max_length=200),
        ),
        migrations.AddField(
            model_name='subject',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2026, 2, 16, 10, 11, 16, 479644, tzinfo=datetime.timezone.utc)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='subject',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='subject',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='chapter',
            name='class_assigned',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chapters', to='admin_tasks.class'),
        ),
        migrations.AlterField(
            model_name='chapter',
            name='is_completed',
            field=models.BooleanField(default=False, help_text='Marked by teacher when completed'),
        ),
        migrations.AlterField(
            model_name='chapter',
            name='name',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='chapter',
            name='subject',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chapters', to='admin_tasks.subject'),
        ),
        migrations.AlterField(
            model_name='class',
            name='name',
            field=models.CharField(max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='feepayment',
            name='amount',
            field=models.DecimalField(decimal_places=2, help_text='Fee amount in INR', max_digits=10),
        ),
        migrations.AlterField(
            model_name='feepayment',
            name='receipt',
            field=models.FileField(blank=True, help_text='Generated PDF receipt', null=True, upload_to='fee_receipts/'),
        ),
        migrations.AlterField(
            model_name='feepayment',
            name='student',
            field=models.ForeignKey(limit_choices_to={'role': 'student'}, on_delete=django.db.models.deletion.CASCADE, related_name='fee_payments', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='notification',
            name='user',
            field=models.ForeignKey(blank=True, help_text='Leave empty for group notifications', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='subject',
            name='classes',
            field=models.ManyToManyField(blank=True, related_name='subjects', to='admin_tasks.class'),
        ),
        migrations.AlterUniqueTogether(
            name='chapter',
            unique_together={('subject', 'class_assigned', 'name')},
        ),
        migrations.CreateModel(
            name='TeacherAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('assigned_date', models.DateTimeField(auto_now_add=True)),
                ('is_active', models.BooleanField(default=True)),
                ('class_assigned', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='teacher_assignments', to='admin_tasks.class')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='teacher_assignments', to='admin_tasks.subject')),
                ('teacher', models.ForeignKey(limit_choices_to={'role': 'teacher'}, on_delete=django.db.models.deletion.CASCADE, related_name='teaching_assignments', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Teacher Assignment',
                'verbose_name_plural': 'Teacher Assignments',
                'ordering': ['teacher', 'subject', 'class_assigned'],
                'unique_together': {('teacher', 'subject', 'class_assigned')},
            },
        ),
    ]
