# Generated by Django 4.2.28 on 2026-02-12 07:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teachers', '0003_option'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendance',
            name='duration_minutes',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='attendance',
            name='from_time',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='attendance',
            name='to_time',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
