# Generated by Django 4.2.28 on 2026-02-18 07:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0004_chapter_class_assigned_chapter_is_completed'),
        ('teachers', '0005_alter_attendance_unique_together_attendance_subject_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assignment',
            name='chapter',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='academics.chapter'),
        ),
        migrations.AlterField(
            model_name='attendance',
            name='class_assigned',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='academics.academicclass'),
        ),
        migrations.AlterField(
            model_name='attendance',
            name='subject',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='academics.subject'),
        ),
        migrations.AlterField(
            model_name='doubt',
            name='subject',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='academics.subject'),
        ),
        migrations.AlterField(
            model_name='teacherassignment',
            name='class_assigned',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='academics.academicclass'),
        ),
        migrations.AlterField(
            model_name='teacherassignment',
            name='subject',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='academics.subject'),
        ),
        migrations.AlterField(
            model_name='test',
            name='chapter',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tests', to='academics.chapter'),
        ),
    ]
