# Generated by Django 4.2.28 on 2026-02-18 15:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0005_classsubject_teacherassignment_alter_chapter_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('teachers', '0006_alter_assignment_chapter_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='attendance',
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name='doubt',
            name='subject',
        ),
        migrations.RemoveField(
            model_name='teacherassignment',
            name='class_assigned',
        ),
        migrations.RemoveField(
            model_name='teacherassignment',
            name='subject',
        ),
        migrations.AddField(
            model_name='attendance',
            name='class_subject',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='academics.classsubject'),
        ),
        migrations.AddField(
            model_name='doubt',
            name='class_subject',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='academics.classsubject'),
        ),
        migrations.AddField(
            model_name='teacherassignment',
            name='class_subject',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='academics.classsubject'),
        ),
        migrations.AlterUniqueTogether(
            name='attendance',
            unique_together={('student', 'class_subject', 'date')},
        ),
        migrations.RemoveField(
            model_name='attendance',
            name='class_assigned',
        ),
        migrations.RemoveField(
            model_name='attendance',
            name='subject',
        ),
    ]
