# Generated by Django 4.2.28 on 2026-02-16 14:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('academics', '0002_alter_academicclass_options_alter_chapter_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Doubt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('doubt_text', models.TextField(blank=True)),
                ('doubt_image', models.ImageField(blank=True, null=True, upload_to='doubts/')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('answered', 'Answered')], default='pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('student', models.ForeignKey(limit_choices_to={'role': 'student'}, on_delete=django.db.models.deletion.CASCADE, related_name='doubts', to=settings.AUTH_USER_MODEL)),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='doubts', to='academics.subject')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='DoubtReply',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reply_text', models.TextField(blank=True)),
                ('reply_image', models.ImageField(blank=True, null=True, upload_to='doubt_replies/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('doubt', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='replies', to='academics.doubt')),
                ('replied_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='doubt_replies', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Doubt Reply',
                'verbose_name_plural': 'Doubt Replies',
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='TeacherSubjectAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('class_assigned', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='teacher_assignments', to='academics.academicclass')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='teacher_assignments', to='academics.subject')),
                ('teacher', models.ForeignKey(limit_choices_to={'role': 'teacher'}, on_delete=django.db.models.deletion.CASCADE, related_name='subject_assignments', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Teacher Subject Assignment',
                'verbose_name_plural': 'Teacher Subject Assignments',
                'ordering': ['teacher', 'class_assigned', 'subject'],
                'unique_together': {('teacher', 'subject', 'class_assigned')},
            },
        ),
    ]
