# Generated by Django 4.2.28 on 2026-02-18 07:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0003_doubt_doubtreply_teachersubjectassignment'),
    ]

    operations = [
        migrations.AddField(
            model_name='chapter',
            name='class_assigned',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='chapters', to='academics.academicclass'),
        ),
        migrations.AddField(
            model_name='chapter',
            name='is_completed',
            field=models.BooleanField(default=False),
        ),
    ]
