# Generated by Django 4.2.28 on 2026-02-18 15:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('academics', '0004_chapter_class_assigned_chapter_is_completed'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClassSubject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('academic_class', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='class_subjects', to='academics.academicclass')),
            ],
            options={
                'ordering': ['academic_class', 'subject'],
            },
        ),
        migrations.CreateModel(
            name='TeacherAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('class_subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='teacher_assignments', to='academics.classsubject')),
                ('teacher', models.ForeignKey(limit_choices_to={'role': 'teacher'}, on_delete=django.db.models.deletion.CASCADE, related_name='teacher_assignments', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['teacher', 'class_subject'],
                'unique_together': {('teacher', 'class_subject')},
            },
        ),
        migrations.AlterModelOptions(
            name='chapter',
            options={'ordering': ['class_subject', 'order', 'name']},
        ),
        migrations.RemoveField(
            model_name='chapter',
            name='class_assigned',
        ),
        migrations.RemoveField(
            model_name='chapter',
            name='subject',
        ),
        migrations.RemoveField(
            model_name='doubt',
            name='subject',
        ),
        migrations.RemoveField(
            model_name='subject',
            name='academic_class',
        ),
        migrations.RemoveField(
            model_name='subject',
            name='teacher',
        ),
        migrations.AlterField(
            model_name='subject',
            name='name',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.DeleteModel(
            name='TeacherSubjectAssignment',
        ),
        migrations.AddField(
            model_name='classsubject',
            name='subject',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='class_subjects', to='academics.subject'),
        ),
        migrations.AddField(
            model_name='chapter',
            name='class_subject',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='chapters', to='academics.classsubject'),
        ),
        migrations.AddField(
            model_name='doubt',
            name='class_subject',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='doubts', to='academics.classsubject'),
        ),
        migrations.AlterUniqueTogether(
            name='classsubject',
            unique_together={('subject', 'academic_class')},
        ),
    ]
