# Generated by Django 4.2.28 on 2026-02-22 10:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0005_classsubject_teacherassignment_alter_chapter_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='academicclass',
            name='name',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
